/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventoryapp;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class InventoryAppModel extends javax.swing.JFrame {

    DefaultTableModel tableModel;

    /**
     * Creates new form InventoryAppModel
     */
    public InventoryAppModel() {
        initComponents();

        Color bg = new Color(211, 241, 223);
        getContentPane().setBackground(bg);

        tableModel = new DefaultTableModel(
                new Object[]{"No.", "Nama Barang", "Kategori", "Status", "Jumlah Stok", "Harga"},
                0 // Initial row count
        );
        OutputTable.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupButtonStatus = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NamaBarang = new javax.swing.JLabel();
        KategoriBarang = new javax.swing.JLabel();
        JumlahStok = new javax.swing.JLabel();
        StatusBarang = new javax.swing.JLabel();
        SpinnerStok = new javax.swing.JSpinner();
        TxtNamaBarang = new javax.swing.JTextField();
        Harga = new javax.swing.JLabel();
        TxtHarga = new javax.swing.JTextField();
        CmbKategori = new javax.swing.JComboBox<>();
        RadioBtnBaru = new javax.swing.JRadioButton();
        RadioBtnBekas = new javax.swing.JRadioButton();
        TxtStok = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        BtnTambah = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnTotalStok = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(211, 241, 223));

        TitleLabel.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(82, 91, 68));
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("INVENTORY APP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TitleLabel)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(211, 241, 223));

        NamaBarang.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        NamaBarang.setForeground(new java.awt.Color(82, 91, 68));
        NamaBarang.setText("Nama Barang:");

        KategoriBarang.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        KategoriBarang.setForeground(new java.awt.Color(82, 91, 68));
        KategoriBarang.setText("Kategori Barang:");

        JumlahStok.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        JumlahStok.setForeground(new java.awt.Color(82, 91, 68));
        JumlahStok.setText("Jumlah Stok:");

        StatusBarang.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        StatusBarang.setForeground(new java.awt.Color(82, 91, 68));
        StatusBarang.setText("Status Barang:");

        Harga.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        Harga.setForeground(new java.awt.Color(82, 91, 68));
        Harga.setText("Harga:");

        CmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elektronik", "Furniture", "Pakaian", "Makanan" }));
        CmbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbKategoriActionPerformed(evt);
            }
        });

        groupButtonStatus.add(RadioBtnBaru);
        RadioBtnBaru.setText("Baru");

        groupButtonStatus.add(RadioBtnBekas);
        RadioBtnBekas.setText("Bekas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JumlahStok, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KategoriBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RadioBtnBaru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SpinnerStok, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioBtnBekas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaBarang)
                    .addComponent(TxtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Harga)
                    .addComponent(TxtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KategoriBarang)
                    .addComponent(CmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusBarang)
                    .addComponent(RadioBtnBaru)
                    .addComponent(RadioBtnBekas))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JumlahStok)
                    .addComponent(SpinnerStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(211, 241, 223));

        BtnTambah.setText("Tambah");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnEdit.setText("Edit");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnTotalStok.setText("Tampilkan Total Stok");
        BtnTotalStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTotalStokActionPerformed(evt);
            }
        });

        BtnReset.setText("Reset");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(BtnHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnReset)
                .addGap(12, 12, 12)
                .addComponent(BtnTotalStok)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTambah)
                    .addComponent(BtnEdit)
                    .addComponent(BtnHapus)
                    .addComponent(BtnTotalStok)
                    .addComponent(BtnReset))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(211, 241, 223));

        OutputTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Nama Barang", "Kategori", "Status", "Jumlah Stok", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OutputTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void resetForm() {
        // Clear Text Fields
        TxtNamaBarang.setText("");
        TxtHarga.setText("");
        TxtStok.setText("");

        // Reset ComboBox and RadioButtons
        CmbKategori.setSelectedIndex(0);
        groupButtonStatus.clearSelection();

        // Reset Spinner
        SpinnerStok.setValue(0);
    }

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        // TODO add your handling code here:
        // Validate Inputs
        if (TxtNamaBarang.getText().isEmpty() || TxtHarga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Barang dan Harga harus diisi!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate Stock Input
        int stok = 0; // Default value
        boolean isSpinnerUsed = false; // To track which input is used

        if (!TxtStok.getText().isEmpty()) {
            // User provided input via TextField
            try {
                stok = Integer.parseInt(TxtStok.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Jumlah Stok di TextField harus berupa angka!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            // Default to Spinner if TextField is empty
            stok = (Integer) SpinnerStok.getValue();
            isSpinnerUsed = true;
        }

        if (stok <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah Stok harus lebih dari 0!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Retrieve Other Inputs
        String namaBarang = TxtNamaBarang.getText();
        String kategori = CmbKategori.getSelectedItem().toString();
        String status = RadioBtnBaru.isSelected() ? "Baru" : "Bekas";
        double harga;

        try {
            harga = Double.parseDouble(TxtHarga.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Add to Table
        int no = tableModel.getRowCount() + 1; // Auto-incrementing number
// Auto-incrementing number
        tableModel.addRow(new Object[]{no, namaBarang, kategori, status, stok, harga});
        // Success Message
        JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan" + "!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

        // Reset Form
        resetForm();
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_BtnResetActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        // TODO add your handling code here:
        // Ensure a row is selected
        int selectedRow = OutputTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih baris yang ingin diubah!", "Kesalahan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validate Inputs
        if (TxtNamaBarang.getText().isEmpty() || TxtHarga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Barang dan Harga harus diisi!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int stok = 0; // Stock Amount
        if (!TxtStok.getText().isEmpty()) {
            // Use TextField if not empty
            try {
                stok = Integer.parseInt(TxtStok.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Jumlah Stok di TextField harus berupa angka!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            // Default to Spinner
            stok = (Integer) SpinnerStok.getValue();
        }

        if (stok <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah Stok harus lebih dari 0!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String namaBarang = TxtNamaBarang.getText();
        String kategori = CmbKategori.getSelectedItem().toString();
        String status = RadioBtnBaru.isSelected() ? "Baru" : "Bekas";
        double harga;

        try {
            harga = Double.parseDouble(TxtHarga.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Update Selected Row in the Table
        tableModel.setValueAt(namaBarang, selectedRow, 1); // Update Item Name
        tableModel.setValueAt(kategori, selectedRow, 2);   // Update Category
        tableModel.setValueAt(status, selectedRow, 3);     // Update Status
        tableModel.setValueAt(stok, selectedRow, 4);       // Update Stock Amount
        tableModel.setValueAt(harga, selectedRow, 5);      // Update Item Cost

        // Success Message
        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

        // Reset Form
        resetForm();

    }//GEN-LAST:event_BtnEditActionPerformed

    private void CmbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbKategoriActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = OutputTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih baris yang ingin dihapus!", "Kesalahan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Confirm Deletion
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus data ini?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Remove Selected Row from Table
            tableModel.removeRow(selectedRow);

            // Success Message
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            // Reset Form
            resetForm();
        }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnTotalStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTotalStokActionPerformed
        // TODO add your handling code here:
        if (tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Tabel kosong. Tidak ada stok yang dapat dihitung!", "Kesalahan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Calculate Total Stock
        int totalStock = 0;
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            totalStock += (int) tableModel.getValueAt(i, 4); // Column 4 = Stock Amount
        }

        // Display Total Stock
        JOptionPane.showMessageDialog(this, "Total Stok: " + totalStock, "Total Stok", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BtnTotalStokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryAppModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryAppModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryAppModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryAppModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryAppModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnTotalStok;
    private javax.swing.JComboBox<String> CmbKategori;
    private javax.swing.JLabel Harga;
    private javax.swing.JLabel JumlahStok;
    private javax.swing.JLabel KategoriBarang;
    private javax.swing.JLabel NamaBarang;
    private javax.swing.JTable OutputTable;
    private javax.swing.JRadioButton RadioBtnBaru;
    private javax.swing.JRadioButton RadioBtnBekas;
    private javax.swing.JSpinner SpinnerStok;
    private javax.swing.JLabel StatusBarang;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField TxtHarga;
    private javax.swing.JTextField TxtNamaBarang;
    private javax.swing.JTextField TxtStok;
    private javax.swing.ButtonGroup groupButtonStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
